version: '3'

services:
  db:
    image: postgres
    restart: always
    ports:
        - "5432:5432"
    volumes:
        - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
  tomcat:
     image: tomcat:9.0.12
     ports:
        - "8888:8080"
